name: Build and Publish
on:
  push:
    tags: 
     - v[0-9]+.[0-9]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - run: npm install
      - run: npm run build
      - run: mv dist release_${{ github.ref_name }}
      - run: zip -r release_${{ github.ref_name }}.zip release_${{ github.ref_name }}
          
      - name: Publish
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release_${{ github.ref_name }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release_${{ github.ref_name }}
